# Generated by Django 4.2.1 on 2023-06-17 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_relationship_manager', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='faultTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Fault Title'),
            preserve_default=False,
        ),
    ]
